### ISSUE TITLE
Unable to POST JSON using XMLHttpRequest

### ISSUE THREAD

**Issue by MasterKale** [formspree/formspree#63] opened 2016-02-02 01:18 UTC
In the interest of minimizing dependencies I'm trying to POST to formspree.io using an XMLHttpRequest object. After poking around it seemed like it should be a simple thing: create a POST request, set the Content Type to JSON, and then send the object containing all of the required values. 

Here's my request implementing all of that:

	var req = new XMLHttpRequest();
	req.open("POST", "//formspree.io/test@email.com");
	req.setRequestHeader("Content-Type", "application/json");
	req.setRequestHeader("Accept", "application/json");
	req.onload = function() { console.log(req.status); };
	req.send(JSON.stringify(payload));

And here's `payload` after validating my form:

> {name: "MK", email: "test@test.com", message: "TEST↵↵MK"}

The request appears to be properly formed - using Chrome's dev tools I can see the request headers and payload and it seems as though everything's being set properly:

![formspree_error](https://cloud.githubusercontent.com/assets/5166470/12736308/f1be38f4-c903-11e5-813c-24fe253ce38c.png)

Unfortunately, whenever I try this method I always get back the following error:

> 400, Can't send an empty form

Out of curiosity (and hoping it was just my ineptness with raw XMLHttpRequest objects), I tweaked the request to just send `payload` as an Object:

    req.send(payload);

Nothing changed, though, except that the JSON object showed up as an `[Object object]` as the **Request Payload** in the Dev Tools.

Am I doing something wrong? If this is an issue with the Formspree website let me know and I'll direct my question over there.

**Comment by MasterKale** [comment] 2016-02-02 02:56
Nevermind, I compared my request to a `$.ajax()` POST and it turns out jQuery doesn't encode the request as `application/json` but as the default of `application/x-www-form-urlencoded`.

I can now send requests via an XMLHttpRequest:

	var form = document.forms[0];
	var formData = new FormData(form);

	var req = new XMLHttpRequest();
	req.open("POST", "//formspree.io/test@email.com");
	req.setRequestHeader("Accept", "application/json");
	req.onload = function() { console.log(req.status); };
	req.send(formData);

**Comment by colevscode** [comment] 2016-02-02 03:28
In other words our api fails when sent json data in the post body?

**Comment by MasterKale** [comment] 2016-02-02 05:58
That's correct, that's what I was experiencing. Based on the fact that the API call worked when I passed in the values as FormData, the issue is probably with the call to [Form.send()](https://github.com/formspree/formspree/blob/master/formspree/forms/views.py#L91):

    if form.confirmed:
        status = form.send(request.form, request.referrer)
    else:
        status = form.send_confirmation(with_data=request.form)

I'm guessing JSON data doesn't appear in the `request` object under the `form` property.

**Comment by fiatjaf** [comment] 2016-02-02 13:15
Our API does not handle JSON data. That's not a bug, only a limitation.

This PR adds support for it: https://github.com/formspree/formspree/pull/37/files

**Comment by rohitdatta** [comment] 2016-02-16 01:29
Closed in #68.

**Closed by rohitdatta** 2016-02-16 01:29 UTC
Labels: enhancement
